### ISSUE TITLE
Can't execute server.js: unexpected reserved word

### ISSUE THREAD

**Issue by CalebEverett** [CalebEverett/react-redux-universal-material#1]
```
[2] ==> �  API is running on port 3030
[2] ==> �  Send requests to http://localhost:3030
[1] [piping] can't execute file: D:\projects\rrum\bin\server.js
[1] [piping] error given was: SyntaxError: Unexpected reserved word
[1]     at exports.runInThisContext (vm.js:53:16)
[1]     at Module._compile (module.js:414:25)
[1]     at Module._extensions..js (module.js:442:10)
[1]     at Object.require.extensions.(anonymous function) [as .jsx] (D:\projects\rrum\node_modules\babel-core\lib\api\register\node.js:214:7)
[1]     at Module.load (module.js:356:32)
[1]     at Module._load (module.js:311:12)
[1]     at Function.module._load (D:\projects\rrum\node_modules\piping\lib\launcher.js:32:16)
[1]     at Module.require (module.js:366:17)
[1]     at require (module.js:385:17)
[1]     at Object.<anonymous> (D:/projects/rrum/src/containers/App/App.js:9:34)
[1] [piping] further repeats of this error will be suppressed...
[0] ./~/react/lib/ReactElement.js
[0] Module parse failed: D:\projects\rrum\node_modules\babel-loader\index.js?{"stage":0,"optional":"runtime","loose":"all","plugins":["react-transform"],"extra":{"react-transform":{"transforms":[{"transform":"react-transform-catch-errors","imports":["react","redbox-react"]},{"transform":"react-transform-hmr","imports":["react"],"locals":["module"]}]}}}!D:\projects\rrum\node_modules\eslint-loader\index.js!D:\projects\rrum\node_modules\react\lib\ReactElement.js Line 25: Unexpected string
[0] You may need an appropriate loader to handle this file type.
[0] | // The Symbol used to tag the ReactElement type. If there is no native Symbol
[0] | // nor polyfill, then a plain number is used for performance.
[0] | var REACT_ELEMENT_TYPE = typeof _Symbol === 'function' && _Symbol.'for' && _Symbol.'for'('react.element') || 0xeac7;
[0] |
[0] | var RESERVED_PROPS = {
[0]  @ ./~/react/lib/ReactMount.js 18:19-44
[0] webpack built 1018bc609cfa3176a08f in 22940ms
```

**Comment by CalebEverett** [comment]
@tomchentw
When I got to that first file, vm.js and look for 53:16, there are only 35 lines in the file and there is no `runInThisContext` function. I searched for the file in the entire project directory to look for another one, but couldn't find one.

**Comment by CalebEverett** [comment]
@tomchentw
I think I figured this out - the addition of the toolbox on the end of the css loader statement was a problem
